{% set name = "DataProperty" %}
{% set version = "0.50.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cad9080e5d1bac85a3bd33a016743537370d524ae683b012345ed9b5b7715f6b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools >=38.3.0
  run:
    - mbstrdecoder >=1.0.0
    - python >=3.5
    - setuptools >=38.3.0
    - typepy >=1.1.1

test:
  imports:
    - dataproperty
    - dataproperty.logger
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/thombashi/DataProperty
  summary: Python library for extract property from data.
  dev_url: https://github.com/thombashi/DataProperty
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
